### ISSUE TITLE
Define schema and logic for routing from STAC collection to titiler

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/stac-explorer#2]
# Need

The UI application will need a way to route tile requests to the correct titiler instance for a given collection. At this time, we assume all collections will have a STAC endpoint. Ideally, we can determine what titiler instance to use based on the STAC endpoint, but this is limiting since we would have to pre-define which titiler instances the application would route requests to.

Being forward looking, we want to make it easy for other STAC systems to use this UI code, so the configuration and logic should allow for the addition of other STAC catalogue endpoints which, presumably, may be associated with their own dynamic tiler instance, which may or may not be titiler-pgstac.

# Proposal

We define a schema for catalogues and collections which includes a few additional values to inform the application as to how to route requests.

Here is the proposed schema:

```yaml
Catalog:
  type: object
  properties:
    endpoint:
      type: string
      format: uri
    isPgstac:
      type: boolean
    titilerEndpoint:
        type: string
        format: uri

Collection:
  type: object
  properties:
    catalog:
      type: string
    id:
      type: string

Catalogs:
  type: object
  additionalProperties:
    $ref: '#/Catalog'

Collections:
  type: array
  items:
    $ref: '#/Collection'

type: object
properties:
  catalogs:
    $ref: '#/Catalogs'
  collections:
    $ref: '#/Collections'
```

And here is an example:

```yaml
catalogs:
  veda:
    endpoint: "https://staging-stac.delta-backend.com"
    titilerEndpoint: "https://staging-raster.delta-backend.com"
    isPgstac: true
  maap:
    endpoint: "https://stac.maap-project.org"
    titilerEndpoint: "https://titiler.maap-project.org"
    isPgstac: false

collections:
  - catalog: "veda"
     id: "mursst-cmr"
  - catalog: "veda"
     id: "combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO" 
  - catalog: "veda"
     id: "nightlights-500m-daily" 
  - catalog: "maap"
     id: "icesat2-boreal"
```

There will also be 2 other titiler instances. At this time we only anticipate one of each, so they may be configured as environment variables:

* titiler-xarray: https://prod-titiler-xarray.delta-backend.com/
* titiler-cmr: TBD

The logic to determine which titiler endpoint to use will be as follows:

1. Make a request to the collection endpoint

```javascript
const data = yaml.load('file.yaml')
const catalogs = data['catalogs']
const collections = data['collections']
# say selected.collection = { id: "mursst-cmr", catalog: "veda" }
collection_data = fetch(`${catalogs[selected.collection.catalog].endpoint}/collections/${selected.collection.id}`)
```

2. If the collection data includes a collection concept id --> make a tile request to TITILER_CMR
3. If the collection data includes an asset type "zarr" --> make a request to titiler-xarray (note, there will need to be additional logic when the collection data includes multiple assets for different groups, in the case of pyramids)
4. If the collection data does not include either of those, make a request to the titiler instance associated with the STAC catalog.
    a. If the titiler is not a pgSTAC instance, a request to the STAC's `/items` endpoint will be required to determine which assets to send to the titiler instance.
    b. If the titiler IS a pgSTAC instance, then we can use the [mosaic register endpoint](https://staging-raster.delta-backend.com/docs#/Mosaic/register_search_mosaic_register_post) with the search parameters, like in the current VEDA UI.

@oliverroick @sharkinsspatial @vincentsarago let me know if 👆🏽 makes sense to you, or you have other ideas, I am open.
