### ISSUE TITLE
Setup CI via github workflows 

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/stac-explorer#40]
The application is deployed via static website hosting to nasa-stac-explorer which is in the veda-smce account. We should have a github workflow which uses the OIDC role for deployment:

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::444055461661:role/github-actions-role-eodc
        role-session-name: stac-explorer-deploy
        role-duration-seconds: 3600
        aws-region: us-west-2
```

to aws s3 cp the output of yarn build to `s3://nasa-stac-explorer` 

There is already a cloudfront distribution and domain setup https://nasa-stac-explorer.delta-backend.com/
